import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { LiveMap } from "@/components/tikis/live-map";
import { SurfaceCard, TikisButton } from "@/components/tikis/ui";
import { useTikisStore } from "@/lib/tikis-store";
import { displayLocation } from "@/shared/tikis-domain";

export default function TrackDeliveryScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { deliveryById } = useTikisStore();
  const delivery = deliveryById(id);
  const trackable = delivery?.status === "pending_confirmation" || delivery?.status === "active" || delivery?.status === "completed";

  if (!delivery || !trackable) {
    return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><View style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="location-disabled" size={30} color="#C23B45" /></View><Text style={styles.emptyTitle}>Suivi indisponible</Text><Text style={styles.emptyText}>Le suivi devient disponible lorsqu’un livreur est retenu pour cette livraison.</Text><TikisButton label="Retour à la livraison" onPress={() => router.back()} style={styles.emptyButton} /></View></SafeAreaView>;
  }

  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.topBar}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#0B1F3A" /></Pressable><View style={styles.heading}><Text style={styles.topTitle}>Suivi en direct</Text><Text style={styles.topSubtitle}>Simulation GPS</Text></View><View style={styles.live}><View style={styles.liveDot} /><Text style={styles.liveLabel}>LIVE</Text></View></View><Text style={styles.title}>{delivery.title}</Text><Text style={styles.subtitle}>{delivery.driverName ?? "Livreur sélectionné"} est en route vers votre destination.</Text><View style={styles.mapWrap}><LiveMap driverName={delivery.driverName ?? "Votre livreur"} /></View><SurfaceCard style={styles.statusCard}><View style={styles.statusIcon}><MaterialIcons name="two-wheeler" size={22} color="#FFFFFF" /></View><View style={styles.statusInfo}><Text style={styles.statusTitle}>Le livreur est en déplacement</Text><Text style={styles.statusText}>La position est automatiquement actualisée pendant la simulation.</Text></View></SurfaceCard><View style={styles.routeCard}><RouteRow icon="inventory-2" label="Récupération" value={displayLocation(delivery.pickup)} color="#007B8B" /><View style={styles.connector} /><RouteRow icon="location-on" label="Destination" value={displayLocation(delivery.dropoff)} color="#E45858" /></View><View style={styles.notice}><MaterialIcons name="science" size={18} color="#006572" /><Text style={styles.noticeText}>Ce parcours est une simulation locale. Lors de l’intégration de production, il sera alimenté par les coordonnées GPS partagées par le livreur.</Text></View></ScrollView></SafeAreaView>;
}

function RouteRow({ icon, label, value, color }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; label: string; value: string; color: string }) { return <View style={styles.routeRow}><View style={[styles.routeIcon, { backgroundColor: color }]}><MaterialIcons name={icon} size={17} color="#FFFFFF" /></View><View style={styles.routeInfo}><Text style={styles.routeLabel}>{label}</Text><Text style={styles.routeValue}>{value}</Text></View></View>; }

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F6F8FC" }, content: { padding: 20, paddingBottom: 36 }, topBar: { flexDirection: "row", alignItems: "center", marginBottom: 23 }, back: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E7ECF2", alignItems: "center", justifyContent: "center" }, heading: { flex: 1, marginLeft: 12 }, topTitle: { color: "#0B1F3A", fontSize: 16, fontWeight: "900" }, topSubtitle: { color: "#697386", fontSize: 11, marginTop: 1 }, live: { flexDirection: "row", alignItems: "center", gap: 5, backgroundColor: "#DCFCE7", paddingHorizontal: 9, height: 27, borderRadius: 14 }, liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#18A572" }, liveLabel: { color: "#147A58", fontSize: 10, fontWeight: "900", letterSpacing: 0.6 }, title: { color: "#0B1F3A", fontSize: 25, fontWeight: "900", lineHeight: 31, letterSpacing: -0.4 }, subtitle: { color: "#697386", fontSize: 14, lineHeight: 21, marginTop: 6 }, mapWrap: { marginTop: 21, shadowColor: "#0B1F3A", shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 4 }, statusCard: { marginTop: 18, flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#0B1F3A", borderColor: "#0B1F3A" }, statusIcon: { width: 43, height: 43, borderRadius: 14, backgroundColor: "#007B8B", alignItems: "center", justifyContent: "center" }, statusInfo: { flex: 1 }, statusTitle: { color: "#FFFFFF", fontSize: 15, fontWeight: "900" }, statusText: { color: "#BED0E7", fontSize: 12, lineHeight: 18, marginTop: 3 }, routeCard: { marginTop: 18, backgroundColor: "#FFFFFF", borderRadius: 18, padding: 15, borderWidth: 1, borderColor: "#E7ECF2" }, routeRow: { flexDirection: "row", alignItems: "center", gap: 10 }, routeIcon: { width: 32, height: 32, borderRadius: 11, alignItems: "center", justifyContent: "center" }, routeInfo: { flex: 1 }, routeLabel: { color: "#8A96A8", fontSize: 10, fontWeight: "900", letterSpacing: 0.6, textTransform: "uppercase" }, routeValue: { color: "#0B1F3A", fontSize: 13, fontWeight: "700", marginTop: 2 }, connector: { width: 1.5, height: 16, backgroundColor: "#C9D4DF", marginLeft: 15, marginVertical: 3 }, notice: { marginTop: 16, padding: 13, borderRadius: 15, backgroundColor: "#E5F6F7", flexDirection: "row", alignItems: "flex-start", gap: 9 }, noticeText: { flex: 1, color: "#35656C", fontSize: 12, lineHeight: 18 }, empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 30 }, emptyIcon: { width: 67, height: 67, borderRadius: 24, backgroundColor: "#FDEBEC", alignItems: "center", justifyContent: "center" }, emptyTitle: { color: "#0B1F3A", fontSize: 22, fontWeight: "900", marginTop: 17 }, emptyText: { color: "#697386", textAlign: "center", fontSize: 14, lineHeight: 21, marginTop: 7 }, emptyButton: { alignSelf: "stretch", marginTop: 24 }, pressed: { opacity: 0.67 },
});

