import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Avatar, SurfaceCard, TikisButton } from "@/components/tikis/ui";
import { haptic } from "@/lib/haptics";
import { isValidReviewText } from "@/lib/review-rules";
import { useTikisStore } from "@/lib/tikis-store";

export default function ReviewDeliveryScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { deliveryById, reviewForDelivery, submitReview } = useTikisStore();
  const delivery = deliveryById(id);
  const existing = reviewForDelivery(id);
  const [rating, setRating] = useState<1 | 2 | 3 | 4 | 5>(5);
  const [comment, setComment] = useState("");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  if (!delivery) return <SafeAreaView style={styles.safe}><View style={styles.missing}><Text style={styles.missingTitle}>Livraison introuvable</Text><TikisButton label="Retour" onPress={() => router.back()} /></View></SafeAreaView>;

  async function save() { if (comment && !isValidReviewText(comment)) { setError("Caractères non autorisés"); haptic.error(); return; } setSaving(true); await new Promise((resolve) => setTimeout(resolve, 350)); const result = submitReview({ deliveryId: id, rating, comment }); setSaving(false); if (!result.ok) { setError(result.message ?? "L’avis n’a pas pu être enregistré."); haptic.error(); return; } haptic.success(); router.replace(`/delivery/${id}` as any); }

  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#0B1F3A" /></Pressable><Text style={styles.topTitle}>Évaluer la course</Text><View style={styles.placeholder} /></View>{existing ? <SurfaceCard style={styles.doneCard}><MaterialIcons name="task-alt" size={28} color="#18A572" /><Text style={styles.doneTitle}>Avis déjà envoyé</Text><Text style={styles.doneText}>Vous avez attribué {existing.rating}/5 à {existing.driverName}.</Text>{existing.comment ? <Text style={styles.quote}>« {existing.comment} »</Text> : null}</SurfaceCard> : <><Text style={styles.eyebrow}>LIVRAISON TERMINÉE</Text><Text style={styles.title}>Comment s’est passée la prestation ?</Text><Text style={styles.subtitle}>Votre avis aide la communauté Tikis à choisir des livreurs de confiance.</Text><SurfaceCard style={styles.driverCard}><Avatar initials={(delivery.driverName ?? "LT").split(" ").map((part) => part[0]).join("")} color="#007B8B" size={56} /><View><Text style={styles.driverName}>{delivery.driverName ?? "Livreur Tikis"}</Text><Text style={styles.deliveryName}>{delivery.title}</Text></View></SurfaceCard><Text style={styles.label}>VOTRE NOTE</Text><View style={styles.stars}>{[1, 2, 3, 4, 5].map((star) => <Pressable key={star} accessibilityRole="button" accessibilityLabel={`${star} étoiles`} onPress={() => { setRating(star as 1 | 2 | 3 | 4 | 5); haptic.selection(); }} style={({ pressed }) => [styles.starButton, pressed && styles.pressed]}><MaterialIcons name={star <= rating ? "star" : "star-outline"} size={39} color={star <= rating ? "#F59E0B" : "#C6D1DC"} /></Pressable>)}</View><Text style={styles.ratingCaption}>{rating === 5 ? "Excellente prestation" : rating >= 4 ? "Très bonne prestation" : rating >= 3 ? "Prestation correcte" : "Prestation à améliorer"}</Text><Text style={styles.label}>VOTRE AVIS <Text style={styles.optional}>(facultatif)</Text></Text><TextInput multiline maxLength={500} value={comment} onChangeText={(value) => { setComment(value); setError(""); }} placeholder="Partagez votre expérience avec ce livreur…" placeholderTextColor="#A1ADBC" style={[styles.comment, error && styles.commentError]} textAlignVertical="top" />{error ? <Text style={styles.error}>{error}</Text> : <Text style={styles.helper}>{comment.length}/500 · Votre avis doit rester respectueux et utile.</Text>}<TikisButton label="Publier mon avis" icon="send" onPress={() => void save()} loading={saving} style={styles.save} /></>}</ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#F6F8FC" }, content: { padding: 20, paddingBottom: 43 }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 23 }, back: { width: 42, height: 42, borderRadius: 15, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E7ECF2", alignItems: "center", justifyContent: "center" }, topTitle: { color: "#0B1F3A", fontSize: 16, fontWeight: "900" }, placeholder: { width: 42 }, eyebrow: { color: "#007B8B", fontSize: 11, fontWeight: "900", letterSpacing: 0.75 }, title: { color: "#0B1F3A", fontSize: 27, lineHeight: 34, fontWeight: "900", marginTop: 6 }, subtitle: { color: "#697386", fontSize: 13, lineHeight: 20, marginTop: 7 }, driverCard: { marginTop: 23, flexDirection: "row", alignItems: "center", gap: 12 }, driverName: { color: "#0B1F3A", fontSize: 16, fontWeight: "900" }, deliveryName: { color: "#697386", fontSize: 12, marginTop: 3 }, label: { color: "#8A96A8", fontSize: 11, fontWeight: "900", letterSpacing: 0.75, marginTop: 25, marginBottom: 10 }, optional: { color: "#A1ADBC", fontWeight: "700" }, stars: { flexDirection: "row", justifyContent: "space-between", backgroundColor: "#FFFFFF", borderRadius: 19, paddingHorizontal: 15, paddingVertical: 15, borderWidth: 1, borderColor: "#E7ECF2" }, starButton: { padding: 2 }, ratingCaption: { color: "#8A5A0E", fontSize: 13, fontWeight: "900", textAlign: "center", marginTop: 10 }, comment: { minHeight: 130, borderRadius: 17, borderWidth: 1, borderColor: "#DDE5ED", backgroundColor: "#FFFFFF", padding: 14, color: "#0B1F3A", fontSize: 14, lineHeight: 20 }, commentError: { borderColor: "#C23B45" }, helper: { color: "#78869A", fontSize: 11, marginTop: 7 }, error: { color: "#C23B45", fontSize: 12, marginTop: 7, fontWeight: "700" }, save: { marginTop: 21 }, doneCard: { alignItems: "center", paddingVertical: 30 }, doneTitle: { color: "#147A58", fontSize: 18, fontWeight: "900", marginTop: 12 }, doneText: { color: "#4F7A6C", fontSize: 13, textAlign: "center", marginTop: 5 }, quote: { color: "#4F7A6C", fontSize: 13, fontStyle: "italic", textAlign: "center", lineHeight: 20, marginTop: 16 }, missing: { flex: 1, alignItems: "center", justifyContent: "center", gap: 18 }, missingTitle: { color: "#0B1F3A", fontSize: 18, fontWeight: "900" }, pressed: { opacity: 0.65 }, });
