import { LegalPage } from "@/components/tikis/legal-page";

export default function TermsScreen() {
  return <LegalPage label="Document légal" title="Conditions d’utilisation" updatedAt="26 août 2026" sections={[
    { title: "Objet et acceptation", paragraphs: ["Les présentes conditions encadrent l’accès et l’utilisation de Tikis, plateforme de mise en relation entre expéditeurs et livreurs indépendants.", "En créant un compte ou en utilisant Tikis, vous confirmez avoir lu et accepté ces conditions. Si vous ne les acceptez pas, vous ne devez pas utiliser la plateforme."] },
    { title: "Compte et vérification", paragraphs: ["L’accès nécessite un numéro de téléphone valide vérifié par code à usage unique. L’utilisateur garantit l’exactitude des informations fournies et conserve la responsabilité de l’accès à son appareil.", "Le type de compte sélectionné à l’inscription — expéditeur ou livreur — est définitif. Tikis peut demander des informations complémentaires afin de prévenir la fraude et de protéger les utilisateurs."] },
    { title: "Livraisons et mise en relation", paragraphs: ["Tikis facilite la mise en relation ; les conditions opérationnelles d’une course, y compris la remise du colis et le prix proposé, sont confirmées dans l’application par les parties concernées.", "L’expéditeur doit fournir des informations exactes sur la livraison. Le livreur doit utiliser un engin approprié, respecter les règles de sécurité et ne pas transporter de biens interdits ou dangereux."] },
    { title: "Frais et Wallet", paragraphs: ["Les frais de mise en relation applicables sont affichés avant confirmation. Lorsqu’une commission est temporairement bloquée ou débitée, Tikis en conserve la traçabilité dans le journal financier du livreur.", "Toute tentative de contournement des frais, de fraude ou de manipulation du Wallet peut entraîner la suspension du compte et l’examen des opérations concernées."] },
    { title: "Comportements interdits", paragraphs: ["Il est interdit d’utiliser Tikis à des fins illicites, de publier des informations trompeuses, d’usurper une identité, de harceler un utilisateur ou d’introduire des données ou du code malveillants.", "Tikis peut limiter, suspendre ou fermer un compte en cas de violation de ces conditions ou lorsque la sécurité de la communauté l’exige."] },
    { title: "Responsabilité et assistance", paragraphs: ["Chaque utilisateur demeure responsable de ses actions, de ses communications et des engagements pris dans le cadre d’une course. Tikis met en œuvre des mesures raisonnables de sécurité et de traçabilité sans garantir l’absence totale d’incident.", "Un signalement peut être transmis depuis le détail d’une livraison. L’assistance Tikis peut être contactée depuis le profil pour toute question ou contestation."] },
  ]} />;
}
