import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { StatusBadge, SurfaceCard } from "@/components/tikis/ui";
import { formatListRouteParts } from "@/lib/geo-rules";
import { useTikisStore } from "@/lib/tikis-store";
import { deliveryStatusMeta, formatMoney, type Delivery } from "@/shared/tikis-domain";

export default function HistoryScreen() {
  const { role, completedDeliveriesForRole, reviewForDelivery } = useTikisStore();
  const deliveries = completedDeliveriesForRole(role);
  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><FlatList data={deliveries} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#0B1F3A" /></Pressable><View><Text style={styles.eyebrow}>VOTRE ACTIVITÉ</Text><Text style={styles.title}>Historique des courses</Text><Text style={styles.subtitle}>{role === "sender" ? "Vos livraisons finalisées et leurs informations." : "Vos courses terminées et vos prestations."}</Text></View></View>} renderItem={({ item }) => <HistoryCard delivery={item} counterpart={role === "sender" ? item.driverName ?? "Livreur Tikis" : item.senderName} review={reviewForDelivery(item.id)} />} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="history" size={34} color="#8A96A8" /><Text style={styles.emptyTitle}>Aucune course terminée</Text><Text style={styles.emptyText}>Vos livraisons finalisées apparaîtront ici avec leur statut et leur date.</Text></View>} /></SafeAreaView>;
}

function HistoryCard({ delivery, counterpart, review }: { delivery: Delivery; counterpart: string; review?: { rating: number } }) { const status = deliveryStatusMeta[delivery.status]; const route = formatListRouteParts(delivery.pickup, delivery.dropoff); return <Pressable onPress={() => router.push(`/delivery/${delivery.id}` as any)} style={({ pressed }) => [pressed && styles.pressed]}><SurfaceCard style={styles.card}><View style={styles.cardTop}><StatusBadge label={status.label} color={status.color} background={status.background} /><Text style={styles.date}>{delivery.scheduledAt}</Text></View><Text style={styles.cardTitle}>{delivery.title}</Text><Text style={styles.counterpart}>{counterpart}</Text><View style={styles.route}><MaterialIcons name="trip-origin" size={16} color="#007B8B" /><Text style={styles.routeText} numberOfLines={1}>{route.pickup}</Text><MaterialIcons name="arrow-forward" size={15} color="#A0ABB9" /><Text style={styles.routeText} numberOfLines={1}>{route.dropoff}</Text></View><View style={styles.cardBottom}><Text style={styles.amount}>{formatMoney(delivery.offeredPrice ?? delivery.estimatedPrice)}</Text>{review ? <View style={styles.rating}><MaterialIcons name="star" size={16} color="#F59E0B" /><Text style={styles.ratingText}>{review.rating}/5</Text></View> : <View style={styles.detailLink}><Text style={styles.detailLinkText}>Voir le détail</Text><MaterialIcons name="chevron-right" size={18} color="#007B8B" /></View>}</View></SurfaceCard></Pressable>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#F6F8FC" }, content: { padding: 20, paddingBottom: 40 }, header: { marginBottom: 21 }, back: { width: 42, height: 42, borderRadius: 15, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E7ECF2", alignItems: "center", justifyContent: "center", marginBottom: 18 }, eyebrow: { color: "#007B8B", fontSize: 11, fontWeight: "900", letterSpacing: 0.75 }, title: { color: "#0B1F3A", fontSize: 27, fontWeight: "900", letterSpacing: -0.5, marginTop: 4 }, subtitle: { color: "#697386", fontSize: 13, lineHeight: 19, marginTop: 5 }, card: { marginBottom: 12 }, cardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, date: { color: "#78869A", fontSize: 11, fontWeight: "700" }, cardTitle: { color: "#0B1F3A", fontSize: 16, fontWeight: "900", marginTop: 14 }, counterpart: { color: "#697386", fontSize: 12, marginTop: 3 }, route: { flexDirection: "row", alignItems: "center", gap: 5, paddingVertical: 13, marginTop: 13, borderTopWidth: 1, borderColor: "#EEF2F6" }, routeText: { color: "#485569", fontSize: 11, flex: 1 }, cardBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, amount: { color: "#007B8B", fontSize: 16, fontWeight: "900" }, rating: { flexDirection: "row", gap: 3, alignItems: "center", backgroundColor: "#FFF7E6", borderRadius: 10, paddingHorizontal: 9, paddingVertical: 5 }, ratingText: { color: "#8A5A0E", fontSize: 12, fontWeight: "900" }, detailLink: { flexDirection: "row", alignItems: "center" }, detailLinkText: { color: "#007B8B", fontSize: 12, fontWeight: "900" }, empty: { alignItems: "center", paddingHorizontal: 30, paddingTop: 65 }, emptyTitle: { color: "#0B1F3A", fontSize: 17, fontWeight: "900", marginTop: 14 }, emptyText: { color: "#78869A", fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 5 }, pressed: { opacity: 0.67 }, });
