import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { StatusBadge, SurfaceCard } from "@/components/tikis/ui";
import { formatListRouteParts } from "@/lib/geo-rules";
import { useTikisStore } from "@/lib/tikis-store";
import { trpc } from "@/lib/trpc";
import { deliveryStatusMeta, formatMoney, formatRelativeDate, type Delivery } from "@/shared/tikis-domain";

export default function HistoryScreen() {
  const { role, profile } = useTikisStore();
  const deliveriesQuery = trpc.deliveries.list.useQuery(undefined, { enabled: Boolean(profile?.phone) });
  const deliveries = (deliveriesQuery.data ?? []).filter((delivery) => delivery.status === "completed");
  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><FlatList data={deliveries} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#111111" /></Pressable><View><Text style={styles.title}>Historique des courses</Text><Text style={styles.subtitle}>{role === "sender" ? "Vos livraisons finalisées et leurs informations." : "Vos courses terminées et vos prestations."}</Text></View></View>} renderItem={({ item }) => <HistoryCard delivery={item} counterpart={role === "sender" ? item.driverName ?? "Livreur Tikis" : item.senderName} />} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name={deliveriesQuery.isLoading ? "hourglass-empty" : "history"} size={34} color="#747474" /><Text style={styles.emptyTitle}>{deliveriesQuery.isLoading ? "Chargement…" : "Aucune course terminée"}</Text><Text style={styles.emptyText}>{deliveriesQuery.error ? "Impossible de charger l’historique. Réessayez dans un instant." : "Vos livraisons finalisées apparaîtront ici avec leur statut et leur date."}</Text></View>} /></SafeAreaView>;
}

function HistoryCard({ delivery, counterpart }: { delivery: Delivery; counterpart: string }) { const status = deliveryStatusMeta[delivery.status]; const route = formatListRouteParts(delivery.pickup, delivery.dropoff); return <Pressable onPress={() => router.push(`/delivery/${delivery.id}` as any)} style={({ pressed }) => [pressed && styles.pressed]}><SurfaceCard style={styles.card}><View style={styles.cardTop}><StatusBadge label={status.label} color={status.color} background={status.background} /><Text style={styles.date}>{formatRelativeDate(delivery.createdAt)}</Text></View><Text style={styles.cardTitle}>{delivery.title}</Text><Text style={styles.counterpart}>{counterpart}</Text><View style={styles.route}><MaterialIcons name="trip-origin" size={16} color="#007B8B" /><Text style={styles.routeText} numberOfLines={1}>{route.pickup}</Text><MaterialIcons name="arrow-forward" size={15} color="#A0ABB9" /><Text style={styles.routeText} numberOfLines={1}>{route.dropoff}</Text></View><View style={styles.cardBottom}><Text style={styles.amount}>{formatMoney(delivery.offeredPrice ?? delivery.estimatedPrice)}</Text><View style={styles.detailLink}><Text style={styles.detailLinkText}>Voir le détail</Text><MaterialIcons name="chevron-right" size={18} color="#007B8B" /></View></View></SurfaceCard></Pressable>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#EEEDF3" }, content: { padding: 16, paddingBottom: 28 }, header: { marginBottom: 16 }, back: { width: 42, height: 42, borderRadius: 8, backgroundColor: "#FFFFFF", borderWidth: 0, alignItems: "center", justifyContent: "center", marginBottom: 13 }, eyebrow: { color: "#007B8B", fontSize: 11, fontWeight: "600", letterSpacing: 0.75 }, title: { color: "#111111", fontSize: 25, fontWeight: "600", letterSpacing: -0.35, marginTop: 3 }, subtitle: { color: "#697386", fontSize: 13, lineHeight: 19, marginTop: 5 }, card: { marginBottom: 8 }, cardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, date: { color: "#78869A", fontSize: 11, fontWeight: "500" }, cardTitle: { color: "#111111", fontSize: 16, fontWeight: "600", marginTop: 11 }, counterpart: { color: "#697386", fontSize: 12, marginTop: 3 }, route: { flexDirection: "row", alignItems: "center", gap: 5, paddingVertical: 10, marginTop: 10, borderTopWidth: 0 }, routeText: { color: "#485569", fontSize: 11, flex: 1 }, cardBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, amount: { color: "#007B8B", fontSize: 16, fontWeight: "600" }, rating: { flexDirection: "row", gap: 3, alignItems: "center", backgroundColor: "#FFF7E6", borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 }, ratingText: { color: "#8A5A0E", fontSize: 12, fontWeight: "600" }, detailLink: { flexDirection: "row", alignItems: "center" }, detailLinkText: { color: "#007B8B", fontSize: 12, fontWeight: "600" }, empty: { alignItems: "center", paddingHorizontal: 30, paddingTop: 52 }, emptyTitle: { color: "#111111", fontSize: 17, fontWeight: "600", marginTop: 14 }, emptyText: { color: "#78869A", fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 5 }, pressed: { opacity: 0.67 }, });
