import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Avatar, SurfaceCard } from "@/components/tikis/ui";
import { useTikisStore } from "@/lib/tikis-store";

export default function ReviewsScreen() { const { role, profile, reviews } = useTikisStore(); const name = profile?.fullName ?? (role === "driver" ? "Antoine Kaboré" : "Aïcha Traoré"); const visibleReviews = role === "driver" ? reviews.filter((review) => review.driverName === name) : reviews; const average = visibleReviews.length ? (visibleReviews.reduce((sum, review) => sum + review.rating, 0) / visibleReviews.length).toFixed(1) : null; return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><FlatList data={visibleReviews} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.top}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#0B1F3A" /></Pressable><Text style={styles.topTitle}>Mes avis</Text><View style={styles.placeholder} /></View><SurfaceCard style={styles.summary}><View style={styles.summaryIcon}><MaterialIcons name="star" size={25} color="#F59E0B" /></View><View><Text style={styles.summaryValue}>{average ? `${average}/5` : "—"}</Text><Text style={styles.summaryLabel}>{visibleReviews.length ? `${visibleReviews.length} avis` : "Aucun avis pour le moment"}</Text></View></SurfaceCard><Text style={styles.heading}>{role === "driver" ? "AVIS REÇUS" : "AVIS ENVOYÉS"}</Text></>} renderItem={({ item }) => <SurfaceCard style={styles.card}><View style={styles.cardTop}><Avatar initials={item.driverName.split(" ").map((part) => part[0]).join("")} color="#007B8B" size={40} /><View style={styles.cardInfo}><Text style={styles.cardName}>{role === "driver" ? "Expéditeur Tikis" : item.driverName}</Text><Text style={styles.date}>{item.createdAt}</Text></View><View style={styles.rating}><MaterialIcons name="star" size={15} color="#F59E0B" /><Text style={styles.ratingText}>{item.rating}/5</Text></View></View>{item.comment ? <Text style={styles.comment}>« {item.comment} »</Text> : <Text style={styles.noComment}>Aucun commentaire détaillé.</Text>}</SurfaceCard>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="star-outline" size={35} color="#8A96A8" /><Text style={styles.emptyTitle}>Aucun avis pour le moment</Text><Text style={styles.emptyText}>{role === "driver" ? "Les avis des expéditeurs apparaîtront après leurs livraisons terminées." : "Les avis envoyés apparaîtront ici après vos évaluations."}</Text></View>} /></SafeAreaView>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#F6F8FC" }, content: { padding: 20, paddingBottom: 40 }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }, back: { width: 42, height: 42, borderRadius: 15, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E7ECF2", alignItems: "center", justifyContent: "center" }, topTitle: { color: "#0B1F3A", fontSize: 17, fontWeight: "900" }, placeholder: { width: 42 }, summary: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#FFF7E6", borderColor: "#F6D48F" }, summaryIcon: { width: 47, height: 47, borderRadius: 16, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, summaryValue: { color: "#8A5A0E", fontSize: 21, fontWeight: "900" }, summaryLabel: { color: "#9A711E", fontSize: 12, marginTop: 2 }, heading: { color: "#8A96A8", fontSize: 11, fontWeight: "900", letterSpacing: 0.7, marginTop: 25, marginBottom: 8 }, card: { marginBottom: 11 }, cardTop: { flexDirection: "row", alignItems: "center", gap: 10 }, cardInfo: { flex: 1 }, cardName: { color: "#0B1F3A", fontSize: 14, fontWeight: "900" }, date: { color: "#78869A", fontSize: 11, marginTop: 2 }, rating: { flexDirection: "row", gap: 3, alignItems: "center", backgroundColor: "#FFF7E6", borderRadius: 9, paddingHorizontal: 8, paddingVertical: 5 }, ratingText: { color: "#8A5A0E", fontSize: 11, fontWeight: "900" }, comment: { color: "#485569", fontSize: 13, fontStyle: "italic", lineHeight: 20, borderTopWidth: 1, borderColor: "#EEF2F6", marginTop: 12, paddingTop: 12 }, noComment: { color: "#9AA5B6", fontSize: 12, marginTop: 12 }, empty: { alignItems: "center", paddingHorizontal: 35, paddingTop: 55 }, emptyTitle: { color: "#0B1F3A", fontSize: 17, fontWeight: "900", marginTop: 13 }, emptyText: { color: "#78869A", fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 5 }, pressed: { opacity: 0.65 }, });
