import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Avatar, SurfaceCard } from "@/components/tikis/ui";
import { useTikisStore } from "@/lib/tikis-store";
import { trpc } from "@/lib/trpc";

export default function ReviewsScreen() { const { role, profile } = useTikisStore(); const reviewsQuery = trpc.reviews.list.useQuery(undefined, { enabled: Boolean(profile?.phone) }); const visibleReviews = reviewsQuery.data ?? []; const average = visibleReviews.length ? (visibleReviews.reduce((sum, review) => sum + review.rating, 0) / visibleReviews.length).toFixed(1) : null; return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><FlatList data={visibleReviews} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.top}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#111111" /></Pressable><Text style={styles.topTitle}>Mes avis</Text><View style={styles.placeholder} /></View><SurfaceCard style={styles.summary}><View style={styles.summaryIcon}><MaterialIcons name="star" size={25} color="#9A6200" /></View><View><Text style={styles.summaryValue}>{average ? `${average}/5` : "—"}</Text><Text style={styles.summaryLabel}>{visibleReviews.length ? `${visibleReviews.length} avis` : reviewsQuery.isLoading ? "Chargement…" : "Aucun avis pour le moment"}</Text></View></SurfaceCard></>} renderItem={({ item }) => <SurfaceCard style={styles.card}><View style={styles.cardTop}><Avatar initials={item.driverName.split(" ").map((part) => part[0]).join("")} color="#007B8B" size={40} /><View style={styles.cardInfo}><Text style={styles.cardName}>{role === "driver" ? "Expéditeur Tikis" : item.driverName}</Text><Text style={styles.date}>{item.createdAt}</Text></View><View style={styles.rating}><MaterialIcons name="star" size={15} color="#9A6200" /><Text style={styles.ratingText}>{item.rating}/5</Text></View></View>{item.comment ? <Text style={styles.comment}>« {item.comment} »</Text> : <Text style={styles.noComment}>Aucun commentaire détaillé.</Text>}</SurfaceCard>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="star-outline" size={35} color="#747474" /><Text style={styles.emptyTitle}>{reviewsQuery.error ? "Chargement indisponible" : "Aucun avis pour le moment"}</Text><Text style={styles.emptyText}>{reviewsQuery.error ? "Impossible de charger vos avis. Réessayez dans un instant." : role === "driver" ? "Les avis des expéditeurs apparaîtront après leurs livraisons terminées." : "Les avis envoyés apparaîtront ici après vos évaluations."}</Text></View>} /></SafeAreaView>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#EEEDF3" }, content: { padding: 16, paddingBottom: 28 }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 14 }, back: { width: 42, height: 42, borderRadius: 8, backgroundColor: "#FFFFFF", borderWidth: 0, alignItems: "center", justifyContent: "center" }, topTitle: { color: "#111111", fontSize: 17, fontWeight: "600" }, placeholder: { width: 42 }, summary: { flexDirection: "row", alignItems: "center", gap: 11, backgroundColor: "#FFF7E6", borderWidth: 0 }, summaryIcon: { width: 43, height: 43, borderRadius: 9, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, summaryValue: { color: "#8A5A0E", fontSize: 20, fontWeight: "600" }, summaryLabel: { color: "#9A711E", fontSize: 12, marginTop: 2 }, heading: { color: "#8A96A8", fontSize: 11, fontWeight: "600", letterSpacing: 0.7, marginTop: 19, marginBottom: 8 }, card: { marginBottom: 8 }, cardTop: { flexDirection: "row", alignItems: "center", gap: 10 }, cardInfo: { flex: 1 }, cardName: { color: "#111111", fontSize: 14, fontWeight: "600" }, date: { color: "#78869A", fontSize: 11, marginTop: 2 }, rating: { flexDirection: "row", gap: 3, alignItems: "center", backgroundColor: "#FFF7E6", borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 }, ratingText: { color: "#8A5A0E", fontSize: 11, fontWeight: "600" }, comment: { color: "#485569", fontSize: 13, fontStyle: "italic", lineHeight: 20, borderTopWidth: 0, marginTop: 10, paddingTop: 0 }, noComment: { color: "#9AA5B6", fontSize: 12, marginTop: 10 }, empty: { alignItems: "center", paddingHorizontal: 35, paddingTop: 50 }, emptyTitle: { color: "#111111", fontSize: 17, fontWeight: "600", marginTop: 13 }, emptyText: { color: "#78869A", fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 5 }, pressed: { opacity: 0.65 }, });
