import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { TikisButton } from "@/components/tikis/ui";
import { SaveAddressDialog } from "@/components/tikis/save-address-dialog";
import { formatDeliveryDetailPlace } from "@/lib/geo-rules";
import { useSearchLocationBias } from "@/hooks/use-search-location-bias";
import { trpc } from "@/lib/trpc";
import type { LocationLabel } from "@/shared/tikis-domain";

export function AddressMapPicker({ visible, targetTitle, initialPlace, onClose, onUse, onFavorite }: { visible: boolean; targetTitle: string; initialPlace: LocationLabel | null; countryCode?: string; onClose: () => void; onUse: (place: LocationLabel) => void; onFavorite: (place: LocationLabel, label: string) => Promise<void> }) {
  const [place, setPlace] = useState<LocationLabel | null>(initialPlace);
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  const [saveDialogVisible, setSaveDialogVisible] = useState(false);
  const initializedForOpening = useRef(false);
  const { mutateAsync: reverseGeocode, isPending: isReversePending } = trpc.geography.reverse.useMutation();
  const { status: gpsStatus, requestBias } = useSearchLocationBias();
  const refreshLocation = useCallback(async () => { const position = await requestBias(); if (!position) { setMessage("Position indisponible ou non autorisée."); return; } try { setMessage("Identification de l’adresse…"); const result = await reverseGeocode(position); setPlace(result ?? null); setMessage(result ? "" : "Adresse introuvable. Utilisez la recherche."); } catch { setMessage("Le géocodage est momentanément indisponible."); } }, [requestBias, reverseGeocode]);
  useEffect(() => { if (!visible) { initializedForOpening.current = false; setMessage(""); return; } if (initializedForOpening.current) return; initializedForOpening.current = true; void refreshLocation(); }, [refreshLocation, visible]);
  const presentation = place ? formatDeliveryDetailPlace(place) : null;
  async function saveFavorite(label: string) { if (!place || saving) return; setSaving(true); try { await onFavorite(place, label); setMessage("Adresse enregistrée dans Mes adresses."); } finally { setSaving(false); } }
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={styles.screen}><View style={styles.mapPreview}><View style={styles.grid} /><View style={styles.marker}><MaterialIcons name="location-on" size={40} color="#FFFFFF" /></View><Text style={styles.webMapNote}>Prévisualisation de la carte</Text></View><SafeAreaView style={styles.controls} edges={["top", "bottom"]}><Text style={styles.instruction}>Utilisez votre position ou revenez à la recherche</Text><View style={styles.floatingControls}><Pressable accessibilityRole="button" accessibilityLabel="Retour à la recherche" onPress={onClose} style={styles.roundButton}><MaterialIcons name="arrow-back" size={25} color="#17212B" /></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Utiliser ma position actuelle" onPress={() => void refreshLocation()} style={styles.roundButton}>{gpsStatus === "loading" || isReversePending ? <ActivityIndicator color="#17212B" /> : <MaterialIcons name="my-location" size={24} color="#17212B" />}</Pressable></View><View style={styles.bottomSheet}><Text style={styles.sheetEyebrow}>{targetTitle.toUpperCase()}</Text>{presentation ? <><Text style={styles.placeTitle}>{presentation.title}</Text><Text style={styles.placeMeta}>{presentation.subtitle}</Text></> : <Text style={styles.placePlaceholder}>Sélectionnez une adresse depuis la recherche.</Text>}{message ? <Text style={styles.message}>{message}</Text> : null}<View style={styles.sheetActions}><TikisButton label="Utiliser" icon="check" onPress={() => place && onUse(place)} disabled={!place || isReversePending} style={styles.useButton} /><Pressable accessibilityRole="button" accessibilityLabel="Ajouter aux adresses enregistrées" onPress={() => setSaveDialogVisible(true)} style={styles.favoriteButton}>{saving ? <ActivityIndicator size="small" color="#A86600" /> : <MaterialIcons name="bookmark-border" size={25} color="#A86600" />}</Pressable></View></View></SafeAreaView><SaveAddressDialog visible={saveDialogVisible} place={place} onClose={() => setSaveDialogVisible(false)} onSave={saveFavorite} /></View></Modal>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#EEEDF3" }, mapPreview: { ...StyleSheet.absoluteFillObject, overflow: "hidden" }, grid: { ...StyleSheet.absoluteFillObject, backgroundColor: "#EEEDF3" }, marker: { position: "absolute", alignSelf: "center", top: "45%", width: 50, height: 50, borderRadius: 10, backgroundColor: "#007B8B", alignItems: "center", justifyContent: "center", borderWidth: 0 }, webMapNote: { position: "absolute", top: "55%", alignSelf: "center", color: "#666666", fontSize: 11, fontWeight: "500" }, controls: { flex: 1, justifyContent: "space-between", paddingTop: 14 }, instruction: { alignSelf: "center", color: "#111111", fontSize: 13, fontWeight: "600", padding: 8, borderRadius: 8, backgroundColor: "rgba(255,255,255,0.9)", overflow: "hidden" }, floatingControls: { flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 14, paddingBottom: 12 }, roundButton: { width: 46, height: 46, borderRadius: 8, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, bottomSheet: { backgroundColor: "#FFFFFF", borderTopLeftRadius: 14, borderTopRightRadius: 14, padding: 16, paddingBottom: 20 }, sheetEyebrow: { color: "#007B8B", fontSize: 10, letterSpacing: 0.7, fontWeight: "600" }, placeTitle: { color: "#111111", fontSize: 16, fontWeight: "600", marginTop: 5 }, placeMeta: { color: "#666666", fontSize: 12, marginTop: 3 }, placePlaceholder: { color: "#666666", fontSize: 13, marginTop: 6 }, message: { color: "#9A6200", fontSize: 11, marginTop: 6 }, sheetActions: { flexDirection: "row", gap: 8, marginTop: 14 }, useButton: { flex: 1, minHeight: 44, borderRadius: 8 }, favoriteButton: { width: 48, minHeight: 44, borderRadius: 8, backgroundColor: "#EEEDF3", alignItems: "center", justifyContent: "center" } });
