import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

type LegalSection = { title: string; paragraphs: string[] };

export function LegalPage({ title, label, updatedAt, sections }: { title: string; label: string; updatedAt: string; sections: LegalSection[] }) {
  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Retour" onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#0B1F3A" /></Pressable><View><Text style={styles.headerLabel}>{label}</Text><Text style={styles.headerTitle}>Tikis</Text></View></View><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Text style={styles.eyebrow}>{label}</Text><Text style={styles.title}>{title}</Text><Text style={styles.updated}>Dernière mise à jour : {updatedAt}</Text></View><View style={styles.notice}><MaterialIcons name="verified-user" size={20} color="#007B8B" /><Text style={styles.noticeText}>Ce document définit les règles d’utilisation de la plateforme Tikis. Il est accessible à tout moment depuis l’inscription.</Text></View>{sections.map((section, index) => <View key={section.title} style={styles.section}><View style={styles.sectionNumber}><Text style={styles.sectionNumberText}>{index + 1}</Text></View><View style={styles.sectionBody}><Text style={styles.sectionTitle}>{section.title}</Text>{section.paragraphs.map((paragraph) => <Text key={paragraph} style={styles.paragraph}>{paragraph}</Text>)}</View></View>)}<Text style={styles.footer}>Pour toute question concernant ce document, contactez l’assistance Tikis depuis votre espace profil.</Text></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F6F8FC" }, header: { minHeight: 62, paddingHorizontal: 20, borderBottomWidth: 1, borderColor: "#E7ECF2", backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#F6F8FC" }, headerLabel: { color: "#007B8B", fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, headerTitle: { color: "#0B1F3A", fontSize: 16, fontWeight: "900", marginTop: 1 }, content: { padding: 20, paddingBottom: 45 }, hero: { paddingTop: 8, paddingBottom: 20 }, eyebrow: { color: "#007B8B", fontSize: 11, fontWeight: "900", letterSpacing: 0.8, textTransform: "uppercase" }, title: { color: "#0B1F3A", fontSize: 28, lineHeight: 34, fontWeight: "900", letterSpacing: -0.5, marginTop: 7 }, updated: { color: "#78869A", fontSize: 12, marginTop: 8 }, notice: { flexDirection: "row", gap: 10, padding: 14, borderRadius: 17, backgroundColor: "#E5F6F7", marginBottom: 22 }, noticeText: { flex: 1, color: "#35656C", fontSize: 12, lineHeight: 18 }, section: { flexDirection: "row", gap: 11, marginBottom: 23 }, sectionNumber: { width: 27, height: 27, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#0B1F3A", marginTop: 1 }, sectionNumberText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, sectionBody: { flex: 1 }, sectionTitle: { color: "#0B1F3A", fontSize: 16, lineHeight: 22, fontWeight: "900", marginBottom: 7 }, paragraph: { color: "#4C596B", fontSize: 13, lineHeight: 20, marginTop: 7 }, footer: { color: "#78869A", fontSize: 12, lineHeight: 18, borderTopWidth: 1, borderColor: "#E1E7ED", paddingTop: 18, marginTop: 2 }, pressed: { opacity: 0.65 },
});
