import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

type LegalSection = { title: string; paragraphs: string[] };

export function LegalPage({ title, label, updatedAt, sections }: { title: string; label: string; updatedAt: string; sections: LegalSection[] }) {
  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Retour" onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#111111" /></Pressable><View><Text style={styles.headerLabel}>{label}</Text><Text style={styles.headerTitle}>Tikis</Text></View></View><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Text style={styles.eyebrow}>{label}</Text><Text style={styles.title}>{title}</Text><Text style={styles.updated}>Dernière mise à jour : {updatedAt}</Text></View><View style={styles.notice}><MaterialIcons name="verified-user" size={20} color="#007B8B" /><Text style={styles.noticeText}>Ce document définit les règles d’utilisation de la plateforme Tikis. Il est accessible à tout moment depuis l’inscription.</Text></View>{sections.map((section, index) => <View key={section.title} style={styles.section}><View style={styles.sectionNumber}><Text style={styles.sectionNumberText}>{index + 1}</Text></View><View style={styles.sectionBody}><Text style={styles.sectionTitle}>{section.title}</Text>{section.paragraphs.map((paragraph) => <Text key={paragraph} style={styles.paragraph}>{paragraph}</Text>)}</View></View>)}<Text style={styles.footer}>Pour toute question concernant ce document, contactez l’assistance Tikis depuis votre espace profil.</Text></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#EEEDF3" }, header: { minHeight: 58, paddingHorizontal: 14, borderBottomWidth: 0, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", gap: 10 }, back: { width: 40, height: 40, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: "#EEEDF3" }, headerLabel: { color: "#007B8B", fontSize: 10, fontWeight: "600", letterSpacing: 0.7 }, headerTitle: { color: "#111111", fontSize: 16, fontWeight: "600", marginTop: 1 }, content: { padding: 16, paddingBottom: 36 }, hero: { paddingTop: 6, paddingBottom: 16 }, eyebrow: { color: "#007B8B", fontSize: 11, fontWeight: "600", letterSpacing: 0.7, textTransform: "uppercase" }, title: { color: "#111111", fontSize: 26, lineHeight: 32, fontWeight: "600", letterSpacing: -0.35, marginTop: 6 }, updated: { color: "#666666", fontSize: 12, marginTop: 7 }, notice: { flexDirection: "row", gap: 9, padding: 12, borderRadius: 9, backgroundColor: "#EEEDF3", marginBottom: 18 }, noticeText: { flex: 1, color: "#666666", fontSize: 12, lineHeight: 18 }, section: { flexDirection: "row", gap: 10, marginBottom: 19 }, sectionNumber: { width: 25, height: 25, borderRadius: 7, alignItems: "center", justifyContent: "center", backgroundColor: "#111111", marginTop: 1 }, sectionNumberText: { color: "#FFFFFF", fontSize: 12, fontWeight: "600" }, sectionBody: { flex: 1 }, sectionTitle: { color: "#111111", fontSize: 15, lineHeight: 21, fontWeight: "600", marginBottom: 6 }, paragraph: { color: "#444444", fontSize: 13, lineHeight: 19, marginTop: 6 }, footer: { color: "#666666", fontSize: 12, lineHeight: 18, borderTopWidth: 0, paddingTop: 14, marginTop: 2 }, pressed: { opacity: 0.67 },
});
