import { useEffect, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { closeDeliveryTrackingChannel, createDeliveryTrackingChannel, type DeliveryPosition } from "@/lib/supabase-tracking";
import type { TrackingEvent } from "@/lib/gps-simulator";

export function LiveMap({ deliveryId, driverName }: { deliveryId: string; driverName: string; onTrackingEvent?: (event: TrackingEvent) => void }) {
  const [position, setPosition] = useState<DeliveryPosition | null>(null);
  useEffect(() => {
    const channel = createDeliveryTrackingChannel(deliveryId, setPosition);
    return () => { void closeDeliveryTrackingChannel(channel); };
  }, [deliveryId]);
  return <View style={styles.container}><View style={styles.grid} /><View style={styles.route}><View style={styles.routeDot} /><View style={styles.routeLine} /><View style={styles.destination}><MaterialIcons name="location-on" size={24} color="#B4232D" /></View></View><View style={styles.content}><View style={[styles.statusPill, position ? styles.statusPillLive : styles.statusPillWaiting]}><View style={[styles.statusDot, position ? styles.statusDotLive : styles.statusDotWaiting]} /><Text style={[styles.statusText, position ? styles.statusTextLive : styles.statusTextWaiting]}>{position ? "POSITION GPS REÇUE" : "EN ATTENTE DU GPS"}</Text></View><View style={styles.icon}><MaterialIcons name={position ? "my-location" : "location-searching"} size={31} color="#FFFFFF" /></View><Text style={styles.title}>{position ? "Position transmise par le livreur" : "Position réelle à venir"}</Text><Text style={styles.text}>{position ? `${driverName} a partagé une position GPS il y a quelques instants.` : `La position de ${driverName} apparaîtra ici dès qu’il ouvrira le suivi sur son appareil.`}</Text>{position ? <Text style={styles.coordinates}>Mise à jour · {new Date(position.recordedAt).toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" })}</Text> : null}</View></View>;
}

const styles = StyleSheet.create({
  container: { height: 360, overflow: "hidden", borderRadius: 10, backgroundColor: "#EEEDF3", position: "relative", alignItems: "center", justifyContent: "center" }, grid: { ...StyleSheet.absoluteFillObject, opacity: 0.55, backgroundColor: "#EEEDF3" }, route: { position: "absolute", width: "76%", height: 120, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, routeDot: { width: 29, height: 29, borderRadius: 8, backgroundColor: "#007B8B", borderWidth: 0 }, routeLine: { height: 4, flex: 1, marginHorizontal: 6, backgroundColor: "#CFCFCF", borderRadius: 2, borderStyle: "dashed" }, destination: { width: 37, height: 37, borderRadius: 9, backgroundColor: "#FFFFFF", justifyContent: "center", alignItems: "center", shadowOpacity: 0, shadowRadius: 0, elevation: 0 }, content: { width: "78%", alignItems: "center", backgroundColor: "rgba(255,255,255,0.94)", padding: 14, borderRadius: 10, borderWidth: 0 }, statusPill: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 9, height: 26, borderRadius: 7 }, statusPillLive: { backgroundColor: "#EEEDF3" }, statusPillWaiting: { backgroundColor: "#EEEDF3" }, statusDot: { width: 6, height: 6, borderRadius: 3 }, statusDotLive: { backgroundColor: "#167A55" }, statusDotWaiting: { backgroundColor: "#9A6200" }, statusText: { fontSize: 9, fontWeight: "600", letterSpacing: 0.55 }, statusTextLive: { color: "#167A55" }, statusTextWaiting: { color: "#9A6200" }, icon: { marginTop: 10, width: 50, height: 50, borderRadius: 10, backgroundColor: "#007B8B", alignItems: "center", justifyContent: "center" }, title: { color: "#111111", fontSize: 15, fontWeight: "600", textAlign: "center", marginTop: 9 }, text: { color: "#666666", fontSize: 12, textAlign: "center", lineHeight: 18, marginTop: 4 }, coordinates: { color: "#007B8B", fontSize: 11, fontWeight: "600", marginTop: 8 },
});
