import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { SurfaceCard } from "@/components/tikis/ui";
import { sanitizePlaceText } from "@/lib/geo-rules";
import { autocompleteQuery, PLACE_AUTOCOMPLETE_DEBOUNCE_MS } from "@/lib/place-autocomplete";
import { trpc } from "@/lib/trpc";
import { useSearchLocationBias } from "@/hooks/use-search-location-bias";
import { locationSubtitle, locationTitle, type LocationLabel, type PlaceSuggestion } from "@/shared/tikis-domain";

type Props = { label: string; tone: "pickup" | "dropoff"; value: LocationLabel | null; countryCode?: string; onChange: (place: LocationLabel) => void };

export function PlacePicker({ label, tone, value, countryCode, onChange }: Props) {
  const [query, setQuery] = useState(value?.name ?? "");
  const [results, setResults] = useState<PlaceSuggestion[]>([]);
  const [message, setMessage] = useState("");
  const search = trpc.geography.search.useMutation();
  const resolve = trpc.geography.resolve.useMutation();
  const searchPlaces = search.mutateAsync;
  const resolvePlace = resolve.mutateAsync;
  const latestSearch = useRef(0);
  const { bias: deviceBias, status: gpsStatus, requestBias } = useSearchLocationBias();
  const accent = tone === "pickup" ? "#007B8B" : "#C23B45";
  const runSearch = useCallback(async (rawQuery: string) => { const clean = autocompleteQuery(rawQuery); if (!clean) { setResults([]); return; } const requestId = ++latestSearch.current; try { setMessage(""); const preferredBias = deviceBias ?? (value ? { latitude: value.latitude, longitude: value.longitude } : null); const places = await searchPlaces({ query: clean, ...(countryCode ? { countryCode } : {}), ...(preferredBias ? { biasLatitude: preferredBias.latitude, biasLongitude: preferredBias.longitude } : {}) }); if (requestId !== latestSearch.current) return; setResults(places); if (!places.length) setMessage("Aucun lieu trouvé."); } catch (cause) { if (requestId === latestSearch.current) setMessage(cause instanceof Error ? cause.message : "La recherche est indisponible."); } }, [countryCode, deviceBias, searchPlaces, value]);
  useEffect(() => { if (!autocompleteQuery(query)) { latestSearch.current += 1; setResults([]); return; } const timer = setTimeout(() => { void runSearch(query); }, PLACE_AUTOCOMPLETE_DEBOUNCE_MS); return () => clearTimeout(timer); }, [query, runSearch]);
  async function selectSuggestion(suggestion: PlaceSuggestion) { try { setMessage("Chargement des coordonnées…"); const place = await resolvePlace({ mapboxId: suggestion.mapboxId, mapboxSessionToken: suggestion.mapboxSessionToken }); latestSearch.current += 1; onChange(place); setResults([]); setMessage(""); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "La sélection du lieu est indisponible."); } }
  async function prioritizeNearbyResults() { const nearby = await requestBias(); setMessage(nearby ? (autocompleteQuery(query) ? "Résultats priorisés autour de votre position actuelle." : "Position activée. Saisissez une adresse pour rechercher à proximité.") : "Position indisponible ou non autorisée. La recherche reste disponible."); }
  return <View style={styles.wrap}><Text style={styles.label}>{label}</Text><SurfaceCard style={styles.card}><View style={styles.searchRow}><MaterialIcons name={tone === "pickup" ? "trip-origin" : "location-on"} size={19} color={accent} /><TextInput value={query} onChangeText={(text) => { setQuery(sanitizePlaceText(text, 120, { preserveTrailingSpace: true })); setMessage(""); }} maxLength={120} placeholder="Rechercher un lieu" placeholderTextColor="#8B97A8" returnKeyType="search" onSubmitEditing={() => void runSearch(query)} style={styles.input} /><Pressable accessibilityRole="button" accessibilityLabel="Prioriser les résultats autour de ma position" onPress={() => void prioritizeNearbyResults()} disabled={gpsStatus === "loading"} style={({ pressed }) => [styles.nearbyButton, (pressed || gpsStatus === "loading") && styles.pressed]}>{gpsStatus === "loading" ? <ActivityIndicator size="small" color="#007B8B" /> : <MaterialIcons name={deviceBias ? "my-location" : "near-me"} size={18} color="#007B8B" />}</Pressable><Pressable onPress={() => void runSearch(query)} disabled={search.isPending} style={({ pressed }) => [styles.searchButton, { backgroundColor: accent }, (pressed || search.isPending) && styles.pressed]}>{search.isPending ? <ActivityIndicator size="small" color="#FFFFFF" /> : <MaterialIcons name="search" size={19} color="#FFFFFF" />}</Pressable></View><View style={styles.preview}><MaterialIcons name="map" size={24} color="#007B8B" /><Text style={styles.previewTitle}>Carte disponible dans l’application mobile</Text><Text style={styles.previewText}>Utilisez l’icône de localisation pour classer les résultats proches de vous.</Text></View>{results.map((place, index) => <Pressable key={`${place.mapboxId}-${index}`} onPress={() => void selectSuggestion(place)} disabled={resolve.isPending} style={({ pressed }) => [styles.result, (pressed || resolve.isPending) && styles.pressed]}><MaterialIcons name="place" size={18} color="#007B8B" /><View style={styles.resultText}><Text style={styles.resultName}>{locationTitle(place)}</Text><Text style={styles.resultMeta} numberOfLines={1}>{locationSubtitle(place)}</Text></View>{resolve.isPending ? <ActivityIndicator size="small" color="#007B8B" /> : <MaterialIcons name="chevron-right" size={20} color="#A1ADBC" />}</Pressable>)}{value ? <View style={styles.selected}><MaterialIcons name="check-circle" size={16} color="#147A58" /><View style={styles.selectedCopy}><Text style={styles.selectedText}>{locationTitle(value)}</Text><Text style={styles.selectedMeta} numberOfLines={1}>{locationSubtitle(value)}</Text></View></View> : null}{message ? <Text style={styles.message}>{message}</Text> : null}</SurfaceCard></View>;
}

const styles = StyleSheet.create({ wrap: { marginBottom: 15 }, label: { color: "#485569", fontWeight: "800", fontSize: 13, marginBottom: 7 }, card: { padding: 10 }, searchRow: { flexDirection: "row", alignItems: "center", minHeight: 48, borderWidth: 1, borderColor: "#DDE5ED", borderRadius: 14, paddingLeft: 11, gap: 8 }, input: { flex: 1, minHeight: 46, color: "#0B1F3A", fontSize: 13, fontWeight: "600" }, nearbyButton: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#E6F5F6" }, searchButton: { width: 40, alignSelf: "stretch", borderRadius: 13, alignItems: "center", justifyContent: "center" }, preview: { minHeight: 104, borderRadius: 14, marginTop: 10, backgroundColor: "#E5F6F7", padding: 16, justifyContent: "center" }, previewTitle: { color: "#0B1F3A", fontSize: 13, fontWeight: "900", marginTop: 8 }, previewText: { color: "#53708A", fontSize: 11, lineHeight: 16, marginTop: 3 }, result: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 11, borderBottomWidth: 1, borderColor: "#EEF2F6" }, resultText: { flex: 1 }, resultName: { color: "#0B1F3A", fontSize: 13, fontWeight: "800" }, resultMeta: { color: "#78869A", fontSize: 11, marginTop: 2 }, selected: { backgroundColor: "#EAF8F1", borderRadius: 12, padding: 10, flexDirection: "row", alignItems: "center", gap: 7, marginTop: 10 }, selectedCopy: { flex: 1, minWidth: 0 }, selectedText: { color: "#147A58", fontSize: 12, fontWeight: "800" }, selectedMeta: { color: "#3E7D66", fontSize: 10.5, marginTop: 1 }, message: { color: "#B45309", fontSize: 11, lineHeight: 16, marginTop: 8 }, pressed: { opacity: 0.68 } });
