import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { SurfaceCard } from "@/components/tikis/ui";
import { sanitizePlaceText } from "@/lib/geo-rules";
import { autocompleteQuery, PLACE_AUTOCOMPLETE_DEBOUNCE_MS } from "@/lib/place-autocomplete";
import { trpc } from "@/lib/trpc";
import type { LocationLabel } from "@/shared/tikis-domain";

type Props = { label: string; tone: "pickup" | "dropoff"; value: LocationLabel | null; onChange: (place: LocationLabel) => void };

export function PlacePicker({ label, tone, value, onChange }: Props) {
  const [query, setQuery] = useState(value?.name ?? "");
  const [results, setResults] = useState<LocationLabel[]>([]);
  const [message, setMessage] = useState("");
  const search = trpc.geography.search.useMutation();
  const searchPlaces = search.mutateAsync;
  const latestSearch = useRef(0);
  const accent = tone === "pickup" ? "#007B8B" : "#C23B45";
  const runSearch = useCallback(async (rawQuery: string) => { const clean = autocompleteQuery(rawQuery); if (!clean) { setResults([]); return; } const requestId = ++latestSearch.current; try { setMessage(""); const places = await searchPlaces({ query: clean }); if (requestId !== latestSearch.current) return; setResults(places); if (!places.length) setMessage("Aucun lieu trouvé."); } catch (cause) { if (requestId === latestSearch.current) setMessage(cause instanceof Error ? cause.message : "La recherche est indisponible."); } }, [searchPlaces]);
  useEffect(() => { if (!autocompleteQuery(query)) { latestSearch.current += 1; setResults([]); return; } const timer = setTimeout(() => { void runSearch(query); }, PLACE_AUTOCOMPLETE_DEBOUNCE_MS); return () => clearTimeout(timer); }, [query, runSearch]);
  return <View style={styles.wrap}><Text style={styles.label}>{label}</Text><SurfaceCard style={styles.card}><View style={styles.searchRow}><MaterialIcons name={tone === "pickup" ? "trip-origin" : "location-on"} size={19} color={accent} /><TextInput value={query} onChangeText={(text) => { setQuery(sanitizePlaceText(text)); setMessage(""); }} maxLength={120} placeholder="Rechercher un lieu" placeholderTextColor="#8B97A8" returnKeyType="search" onSubmitEditing={() => void runSearch(query)} style={styles.input} /><Pressable onPress={() => void runSearch(query)} disabled={search.isPending} style={({ pressed }) => [styles.searchButton, { backgroundColor: accent }, (pressed || search.isPending) && styles.pressed]}>{search.isPending ? <ActivityIndicator size="small" color="#FFFFFF" /> : <MaterialIcons name="search" size={19} color="#FFFFFF" />}</Pressable></View><View style={styles.preview}><MaterialIcons name="map" size={24} color="#007B8B" /><Text style={styles.previewTitle}>Carte disponible dans l’application mobile</Text><Text style={styles.previewText}>Sur iOS et Android, touchez la carte Google pour choisir un point précis.</Text></View>{results.map((place, index) => <Pressable key={`${place.googlePlaceId ?? place.latitude}-${index}`} onPress={() => { latestSearch.current += 1; onChange(place); setResults([]); setMessage(""); }} style={({ pressed }) => [styles.result, pressed && styles.pressed]}><MaterialIcons name="place" size={18} color="#007B8B" /><View style={styles.resultText}><Text style={styles.resultName}>{place.name}</Text><Text style={styles.resultMeta} numberOfLines={1}>{[place.district, place.city, place.formattedAddress].filter(Boolean).join(" · ")}</Text></View><MaterialIcons name="chevron-right" size={20} color="#A1ADBC" /></Pressable>)}{value ? <View style={styles.selected}><MaterialIcons name="check-circle" size={16} color="#147A58" /><Text style={styles.selectedText}>{[value.name, value.district, value.city].filter(Boolean).join(" · ")}</Text></View> : null}{message ? <Text style={styles.message}>{message}</Text> : null}</SurfaceCard></View>;
}

const styles = StyleSheet.create({ wrap: { marginBottom: 15 }, label: { color: "#485569", fontWeight: "800", fontSize: 13, marginBottom: 7 }, card: { padding: 10 }, searchRow: { flexDirection: "row", alignItems: "center", minHeight: 48, borderWidth: 1, borderColor: "#DDE5ED", borderRadius: 14, paddingLeft: 11, gap: 8 }, input: { flex: 1, minHeight: 46, color: "#0B1F3A", fontSize: 13, fontWeight: "600" }, searchButton: { width: 40, alignSelf: "stretch", borderRadius: 13, alignItems: "center", justifyContent: "center" }, preview: { minHeight: 104, borderRadius: 14, marginTop: 10, backgroundColor: "#E5F6F7", padding: 16, justifyContent: "center" }, previewTitle: { color: "#0B1F3A", fontSize: 13, fontWeight: "900", marginTop: 8 }, previewText: { color: "#53708A", fontSize: 11, lineHeight: 16, marginTop: 3 }, result: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 11, borderBottomWidth: 1, borderColor: "#EEF2F6" }, resultText: { flex: 1 }, resultName: { color: "#0B1F3A", fontSize: 13, fontWeight: "800" }, resultMeta: { color: "#78869A", fontSize: 11, marginTop: 2 }, selected: { backgroundColor: "#EAF8F1", borderRadius: 12, padding: 10, flexDirection: "row", alignItems: "center", gap: 7, marginTop: 10 }, selectedText: { flex: 1, color: "#147A58", fontSize: 12, fontWeight: "800" }, message: { color: "#B45309", fontSize: 11, lineHeight: 16, marginTop: 8 }, pressed: { opacity: 0.68 } });
