import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { Modal, StyleSheet, Text, TextInput, View } from "react-native";
import { TikisButton } from "@/components/tikis/ui";
import { sanitizePlaceText } from "@/lib/geo-rules";
import { locationSubtitle, locationTitle, type LocationLabel } from "@/shared/tikis-domain";

export function SaveAddressDialog({ visible, place, onClose, onSave }: { visible: boolean; place: LocationLabel | null; onClose: () => void; onSave: (label: string) => Promise<void> }) {
  const [label, setLabel] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { if (visible) { setLabel(""); setError(""); } }, [visible]);
  async function save() { if (!place || !label.trim() || saving) return; setSaving(true); setError(""); try { await onSave(label.trim()); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible d’enregistrer cette adresse."); } finally { setSaving(false); } }
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={() => !saving && onClose()}><View style={styles.overlay}><View style={styles.dialog}><View style={styles.icon}><MaterialIcons name="bookmark-add" size={25} color="#9A6200" /></View><Text style={styles.title}>Enregistrer cette adresse</Text><Text style={styles.subtitle}>Donnez-lui un nom simple pour la retrouver plus vite.</Text>{place ? <View style={styles.address}><Text style={styles.addressTitle} numberOfLines={1}>{locationTitle(place)}</Text><Text style={styles.addressMeta} numberOfLines={2}>{locationSubtitle(place)}</Text></View> : null}<Text style={styles.label}>LIBELLÉ</Text><TextInput value={label} onChangeText={(value) => setLabel(sanitizePlaceText(value, 80, { preserveTrailingSpace: true }))} placeholder="Ex. Maison ou Bureau" placeholderTextColor="#9AA5B6" style={styles.input} maxLength={80} autoFocus returnKeyType="done" onSubmitEditing={() => void save()} />{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.actions}><TikisButton label="Annuler" variant="secondary" onPress={onClose} disabled={saving} style={styles.action} /><TikisButton label="Enregistrer" icon="bookmark-add" onPress={() => void save()} loading={saving} loadingLabel="Enregistrement…" disabled={!label.trim()} style={styles.action} /></View></View></View></Modal>;
}

const styles = StyleSheet.create({ overlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.42)", alignItems: "center", justifyContent: "center", padding: 22 }, dialog: { width: "100%", maxWidth: 400, backgroundColor: "#FFFFFF", borderRadius: 14, padding: 18 }, icon: { width: 44, height: 44, borderRadius: 10, backgroundColor: "#EEEDF3", alignItems: "center", justifyContent: "center", alignSelf: "center", marginBottom: 10 }, title: { color: "#111111", fontSize: 17, fontWeight: "600", textAlign: "center" }, subtitle: { color: "#666666", fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 6 }, address: { marginTop: 14, padding: 12, borderRadius: 10, backgroundColor: "#EEEDF3" }, addressTitle: { color: "#111111", fontWeight: "600", fontSize: 13 }, addressMeta: { color: "#666666", fontSize: 11, lineHeight: 16, marginTop: 3 }, label: { color: "#747474", fontSize: 10, fontWeight: "600", letterSpacing: 0.7, marginTop: 15, marginBottom: 6 }, input: { minHeight: 46, borderWidth: 0, borderRadius: 9, backgroundColor: "#EEEDF3", color: "#111111", fontSize: 15, fontWeight: "500", paddingHorizontal: 12 }, error: { color: "#B4232D", fontSize: 11, lineHeight: 16, marginTop: 6 }, actions: { flexDirection: "row", gap: 8, marginTop: 16 }, action: { flex: 1, minHeight: 44 } });
