import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { Modal, StyleSheet, Text, TextInput, View } from "react-native";
import { TikisButton } from "@/components/tikis/ui";
import { sanitizePlaceText } from "@/lib/geo-rules";
import { locationSubtitle, locationTitle, type LocationLabel } from "@/shared/tikis-domain";

export function SaveAddressDialog({ visible, place, onClose, onSave }: { visible: boolean; place: LocationLabel | null; onClose: () => void; onSave: (label: string) => Promise<void> }) {
  const [label, setLabel] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { if (visible) { setLabel(""); setError(""); } }, [visible]);
  async function save() { if (!place || !label.trim() || saving) return; setSaving(true); setError(""); try { await onSave(label.trim()); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible d’enregistrer cette adresse."); } finally { setSaving(false); } }
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={() => !saving && onClose()}><View style={styles.overlay}><View style={styles.dialog}><View style={styles.icon}><MaterialIcons name="bookmark-add" size={25} color="#A86600" /></View><Text style={styles.title}>Enregistrer cette adresse</Text><Text style={styles.subtitle}>Donnez-lui un nom simple pour la retrouver plus vite.</Text>{place ? <View style={styles.address}><Text style={styles.addressTitle} numberOfLines={1}>{locationTitle(place)}</Text><Text style={styles.addressMeta} numberOfLines={2}>{locationSubtitle(place)}</Text></View> : null}<Text style={styles.label}>LIBELLÉ</Text><TextInput value={label} onChangeText={(value) => setLabel(sanitizePlaceText(value, 80, { preserveTrailingSpace: true }))} placeholder="Ex. Maison ou Bureau" placeholderTextColor="#9AA5B6" style={styles.input} maxLength={80} autoFocus returnKeyType="done" onSubmitEditing={() => void save()} />{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.actions}><TikisButton label="Annuler" variant="secondary" onPress={onClose} disabled={saving} style={styles.action} /><TikisButton label="Enregistrer" icon="bookmark-add" onPress={() => void save()} loading={saving} loadingLabel="Enregistrement…" disabled={!label.trim()} style={styles.action} /></View></View></View></Modal>;
}

const styles = StyleSheet.create({ overlay: { flex: 1, backgroundColor: "rgba(11,31,58,0.44)", alignItems: "center", justifyContent: "center", padding: 24 }, dialog: { width: "100%", maxWidth: 400, backgroundColor: "#FFFFFF", borderRadius: 24, padding: 21 }, icon: { width: 49, height: 49, borderRadius: 16, backgroundColor: "#FFF4D8", alignItems: "center", justifyContent: "center", alignSelf: "center", marginBottom: 10 }, title: { color: "#0B1F3A", fontSize: 18, fontWeight: "900", textAlign: "center" }, subtitle: { color: "#697386", fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 7 }, address: { marginTop: 16, padding: 12, borderRadius: 14, backgroundColor: "#F5F8FA" }, addressTitle: { color: "#243244", fontWeight: "900", fontSize: 13 }, addressMeta: { color: "#718095", fontSize: 11, lineHeight: 16, marginTop: 3 }, label: { color: "#596779", fontSize: 10, fontWeight: "900", letterSpacing: 0.7, marginTop: 17, marginBottom: 7 }, input: { minHeight: 50, borderWidth: 1, borderColor: "#DCE5ED", borderRadius: 14, color: "#0B1F3A", fontSize: 15, fontWeight: "700", paddingHorizontal: 13 }, error: { color: "#C23B45", fontSize: 11, lineHeight: 16, marginTop: 7 }, actions: { flexDirection: "row", gap: 10, marginTop: 18 }, action: { flex: 1, minHeight: 47 } });
