import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { KeyboardAvoidingView, Modal, Platform, StyleSheet, Text, TextInput, View } from "react-native";
import { TikisButton } from "@/components/tikis/ui";
import { sanitizePlaceText } from "@/lib/geo-rules";
import { useThemeColors } from "@/lib/use-theme-colors";
import { locationSubtitle, locationTitle, type LocationLabel } from "@/shared/tikis-domain";

export function SaveAddressDialog({ visible, place, onClose, onSave }: { visible: boolean; place: LocationLabel | null; onClose: () => void; onSave: (label: string) => Promise<void> }) {
  const { colors: theme, isDark } = useThemeColors();
  const [label, setLabel] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { if (visible) { setLabel(""); setError(""); } }, [visible]);
  async function save() { if (!place || !label.trim() || saving) return; setSaving(true); setError(""); try { await onSave(label.trim()); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible d’enregistrer cette adresse."); } finally { setSaving(false); } }
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={() => !saving && onClose()}><View style={[styles.overlay, { backgroundColor: theme.overlay }]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.keyboard}><View style={[styles.dialog, { backgroundColor: theme.surface }]}><View style={[styles.icon, { backgroundColor: isDark ? "#312515" : "#F8E8CE" }]}><MaterialIcons name="bookmark-add" size={25} color={theme.primary} /></View><Text style={[styles.title, { color: theme.foreground }]}>Enregistrer cette adresse</Text>{place ? <View style={[styles.address, { backgroundColor: theme.input }]}><Text style={[styles.addressTitle, { color: theme.foreground }]} numberOfLines={1}>{locationTitle(place)}</Text><Text style={[styles.addressMeta, { color: theme.muted }]} numberOfLines={2}>{locationSubtitle(place)}</Text></View> : null}<Text style={[styles.label, { color: theme.muted }]}>LIBELLÉ</Text><TextInput value={label} onChangeText={(value) => { setLabel(sanitizePlaceText(value, 80, { preserveTrailingSpace: true })); setError(""); }} placeholder="Ex. Maison ou Bureau" placeholderTextColor={theme.muted} style={[styles.input, { backgroundColor: theme.input, color: theme.foreground, borderColor: error ? theme.error : theme.border }]} maxLength={80} autoFocus returnKeyType="done" onSubmitEditing={() => void save()} />{error ? <Text style={[styles.error, { color: theme.error }]}>{error}</Text> : null}<View style={styles.actions}><TikisButton label="Annuler" variant="secondary" onPress={onClose} disabled={saving} style={styles.action} /><TikisButton label="Enregistrer" icon="bookmark-add" onPress={() => void save()} loading={saving} loadingLabel="Enregistrement…" disabled={!label.trim()} style={styles.action} /></View></View></KeyboardAvoidingView></View></Modal>;
}

const styles = StyleSheet.create({ overlay: { flex: 1, alignItems: "center", justifyContent: "center", padding: 22 }, keyboard: { width: "100%", maxWidth: 400 }, dialog: { width: "100%", borderRadius: 11, padding: 18 }, icon: { width: 44, height: 44, borderRadius: 8, alignItems: "center", justifyContent: "center", alignSelf: "center", marginBottom: 10 }, title: { fontSize: 17, fontWeight: "600", textAlign: "center" }, address: { marginTop: 14, padding: 12, borderRadius: 8 }, addressTitle: { fontWeight: "600", fontSize: 13 }, addressMeta: { fontSize: 11, lineHeight: 16, marginTop: 3 }, label: { fontSize: 10, fontWeight: "600", letterSpacing: 0.7, marginTop: 15, marginBottom: 6 }, input: { minHeight: 46, borderWidth: 1, borderRadius: 8, fontSize: 15, paddingHorizontal: 12 }, error: { fontSize: 11, lineHeight: 16, marginTop: 6 }, actions: { flexDirection: "row", gap: 8, marginTop: 16 }, action: { flex: 1, minHeight: 44 } });
